# Generated by Django 5.2.8 on 2026-04-14 17:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(choices=[('soporte', 'Soporte técnico'), ('legal', 'Consulta legal'), ('reporte', 'Reportar usuario'), ('sugerencia', 'Sugerencia'), ('otro', 'Otro motivo')], max_length=20)),
                ('message', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'db_table': 'contact_message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=1, help_text='Positivo = crédito recibido / Negativo = crédito pagado', max_digits=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.trade'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('debit', 'Débito'), ('credit', 'Crédito'), ('bonus', 'Bono de onboarding')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='credits',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8),
        ),
    ]
