# Generated by Django 5.2.8 on 2026-04-17 11:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactmessage_transaction_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'En línea'), ('away', 'Ausente')], default='online', max_length=10)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('typing_at', models.DateTimeField(blank=True, null=True)),
                ('typing_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.conversation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presencia de usuario',
                'verbose_name_plural': 'Presencias de usuarios',
                'db_table': 'user_presence',
            },
        ),
    ]
