# Generated by Django 5.2.8 on 2026-05-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='max_trade_distance_km',
            field=models.PositiveIntegerField(default=100, help_text='Máxima distancia aceptable para intercambios (km)'),
        ),
        migrations.AddField(
            model_name='user',
            name='search_my_city_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='search_radius_km',
            field=models.PositiveIntegerField(default=25, help_text='Radio de búsqueda por defecto en km'),
        ),
        migrations.AddField(
            model_name='user',
            name='trade_my_city_only',
            field=models.BooleanField(default=False),
        ),
    ]
