# Generated by Django 5.2.8 on 2026-05-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_trade_negotiation_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='badge',
            field=models.CharField(blank=True, choices=[('gold', 'Oro'), ('silver', 'Plata'), ('bronze', 'Bronce'), ('', 'Ninguno')], default='', max_length=10),
        ),
    ]
