# Generated by Django 5.2.8 on 2026-05-13 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_avatar_image_alter_user_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='auto_cancel_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='end_confirmations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trade',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_started', to=settings.AUTH_USER_MODEL),
        ),
    ]
