# Generated by Django 5.2.8 on 2026-06-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_trade_auto_cancel_at_trade_end_confirmations_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='user',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='UserSkill',
        ),
    ]
