# Generated by Django 5.2.8 on 2025-11-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=75)),
                ('apellidos', models.TextField(max_length=150)),
                ('dni', models.TextField(max_length=9, unique=True)),
                ('edad', models.PositiveIntegerField(max_length=150)),
                ('sexo', models.IntegerField(choices=[(0, 'Masculino'), (1, 'Femenino'), (2, 'Otro')], default=2)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
