# Generated by Django 5.2.8 on 2025-11-27 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuario_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
                ('descripcion', models.TextField(default='Sin descripción', max_length=200)),
            ],
            options={
                'db_table': 'etiqueta',
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[(0, 'Masculino'), (1, 'Femenino'), (2, 'Otro')], default=2),
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=30, unique=True)),
                ('descripcion', models.TextField(default='Sin descripción', max_length=200)),
                ('etiquetas', models.ManyToManyField(to='api.etiqueta')),
            ],
            options={
                'db_table': 'habilidad',
            },
        ),
        migrations.CreateModel(
            name='Intercambio',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('torrijas', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateTimeField(auto_now=True)),
                ('fecha_final', models.DateTimeField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to='api.usuario')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitante', to='api.usuario')),
            ],
            options={
                'db_table': 'intercambio',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('texto', models.TextField(max_length=500)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('intercambio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.intercambio')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario')),
            ],
            options={
                'db_table': 'mensaje',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=70)),
                ('descripcion', models.TextField(blank=True, max_length=300)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.habilidad')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('torrijas', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('intercambio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.intercambio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'transaccion',
            },
        ),
        migrations.CreateModel(
            name='UsuarioHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(blank=True, choices=[(0, 'Básico'), (1, 'Intermedio'), (2, 'Experto')], default=0, max_length=20)),
                ('anios_experiencia', models.PositiveIntegerField(default=0)),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.habilidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='api.usuario')),
            ],
            options={
                'db_table': 'usuario_habilidad',
            },
        ),
        migrations.AddConstraint(
            model_name='intercambio',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_final', models.F('fecha_inicio'))), name='fechas_validas'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariohabilidad',
            unique_together={('usuario', 'habilidad')},
        ),
    ]
