# Generated by Django 5.2.8 on 2025-11-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_etiqueta_alter_usuario_dni_alter_usuario_sexo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambio',
            name='estado',
            field=models.CharField(blank=True, choices=[(0, 'Solicitado'), (1, 'En negociación'), (2, 'Aceptado'), (3, 'Cancelado')], default=0),
        ),
    ]
